spring.application.name=bibliopelis

server.port=8080
#esta cadena de conexion es para conectarse con una app dentro de un contenedor y una base tambien
#spring.datasource.url=jdbc:postgresql://host.docker.internal:5454/apppruebas-db
#spring.datasource.username=apppruebas-user
#spring.datasource.password=apppruebas-psw
# Configuración de la base de datos PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5430/postgres
spring.datasource.username=postgres
spring.datasource.password=password_seguro
#spring.datasource.url=jdbc:postgresql://dpg-d6p8hc1j16oc738ulnqg-a.frankfurt-postgres.render.com:5432/movies_db_jd7a
#spring.datasource.username=movies_db_jd7a_user
#spring.datasource.password=uLVxsgktD2iM9cqlc1S0JkmPDqxDTZA5
#spring.datasource.url=jdbc:postgresql://ep-green-poetry-alcmgg12-pooler.c-3.eu-central-1.aws.neon.tech:5432/neondb?sslmode=require
#spring.datasource.username=neondb_owner
#spring.datasource.password=npg_W5VFNZv4tDrA
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
logging.level.com.zaxxer.hikari=DEBUG
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=5
