spring.application.name=bibliopelis
# Puerto del servidor (opcional)
server.port=8080
# Configuración de la base de datos PostgreSQL
#spring.datasource.url=jdbc:postgresql://localhost:5432/movies-db
#spring.datasource.username=app-movies
#spring.datasource.password=app-movies
spring.datasource.url=jdbc:postgresql://dpg-d6p8hc1j16oc738ulnqg-a.frankfurt-postgres.render.com:5432/movies_db_jd7a
spring.datasource.username=movies_db_jd7a_user
spring.datasource.password=uLVxsgktD2iM9cqlc1S0JkmPDqxDTZA5
spring.datasource.driver-class-name=org.postgresql.Driver
# Configuración JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
# Log del Hikari (Pool de conexiones)
# Con este atributo en modo DEBUG da información del POOL
logging.level.com.zaxxer.hikari=DEBUG
# Pool
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=5
